#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /var/{www,log/nginx} \
    /run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# copy config files
echo "overwrite /etc/nginx/nginx.conf" && \
cp /defaults/nginx.conf /etc/nginx/nginx.conf

[[ ! -f /etc/nginx/conf.d/symfony.conf ]] && \
    echo "overwrite /etc/nginx/conf.d/symfony.conf" && \
	cp /defaults/symfony.conf /etc/nginx/conf.d/symfony.conf

# use Rancher resolver if it respond
if ping -c 1 -W 1 169.254.169.250; then
   echo "using Rancher resolver"
   sed -i s/127.0.0.11/169.254.169.250/g /etc/nginx/conf.d/*
fi

# permissions
find /var -type d -path /var/www/symfony/public -prune -o -print0 | xargs -0 chown app:app

chown -R app:app \
	/etc/nginx \
	/var/lib/nginx \
	/var/tmp/nginx

chmod -R g+w \
    /etc/nginx \

chmod -R 644 /etc/logrotate.d
